# This is a basic workflow to help you get started with Actions

name: Github action is awesome

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  #schedule:
    #- cron: '*/5 * * * *'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    #- name: send telegram 
      #run: curl "https://api.telegram.org/${{ secrets.BOTTOKEN }}/sendMessage?chat_id=${{ secrets.CHATID }}&text=欢迎关注公众号 Brick713的小黑屋"
    - name: send tiem
      run: |
        $nowtime=`ate +%H`
        curl "https://api.telegram.org/${{ secrets.BOTTOKEN }}/sendMessage?chat_id=${{ secrets.CHATID }}&text=$nowtime"
      shell: bash 
